# Generated by Django 4.1.3 on 2022-11-20 05:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, blank=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('thumb', models.ImageField(blank=True, upload_to='posts/')),
                ('description', models.CharField(max_length=200)),
                ('text', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='publish date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('next_post', models.ManyToManyField(blank=True, to='core.post')),
                ('previous_post', models.ManyToManyField(blank=True, to='core.post')),
                ('tags', models.ManyToManyField(to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pagina Principal', max_length=50)),
                ('text_alt_project', models.CharField(blank=True, max_length=200)),
                ('text_alt_project_in_progress', models.CharField(blank=True, max_length=200)),
                ('finished_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_project', to='core.post')),
                ('ongoing_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ongoing_project', to='core.post')),
            ],
        ),
    ]
